language: scala

script:
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test

before_cache:
  - rm -fv "$HOME/.ivy2/.sbt.ivy.lock"
  - find "$HOME/.ivy2/cache" -name "ivydata-*.properties" -print -delete
  - find "$HOME/.sbt"        -name "*.lock"               -print -delete

cache:
  directories:
    - "$HOME/.cache/coursier"
    - "$HOME/.coursier"
    - "$HOME/.ivy2/cache"
    - "$HOME/.m2"
    - "$HOME/.sbt"
