language: scala

sudo: false

jdk:
- oraclejdk8

addons:
  apt:
    packages:
    - oracle-java8-installer

env:
  global:
#  - secure: "ENCRYPTED_PGP_PASSPHRASE"
#  - secure: "ENCRYPTED_GITHUB_TOKEN"

before_install:
#- openssl aes-256-cbc -K $encrypted_4a09436dfeda_key -iv $encrypted_4a09436dfeda_iv -in travis/secring.asc.enc -out travis/secring.asc -d

script:
- sbt scripted

after_success:
- if [ "$TRAVIS_PULL_REQUEST" = 'false' ] && [ -n "$TRAVIS_TAG" ]; then
  sbt publishSigned githubRelease;
  fi;

before_cache:
- find "$HOME/.ivy2/cache" -name "ivydata-*.properties" -print -delete
- find "$HOME/.sbt"        -name "*.lock"               -print -delete

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
